# AlternativeAEF config

# Patch future/rusher packet fly
PreventPacketFly: true
# Max teleport packets per 10 seconds, this is how the packet fly works, 25 is usually fine, if you go lower players may get stuck.
MaxTeleportPacketsPer10Seconds: 25
LogPacketFlyEvents: false

# Patches the future/rusherhack/kamiblue 2b2t elytra fly exploit
PatchPacketElytraFly: true
# Recommended to not go lower as there could be false positives.
MaxElytraOpensPer10Seconds: 25 # Will only allow players to go about 85km/h on kami blue, and won't even work on rusherhack.

# Patch futureclient/rusherhack boat fly exploit
# This does not affect boats at all! Even on land.
BoatflyPatch: true
MaxEntityPacketsPer10Seconds: 15
LogBoatFlyEvents: true

PreventBurrow: true # Preliminary burrow patch, please test. Makes players take damage every time they move when their feet are in a block
BurrowDamageWhenMoving: 1 # Half a heart of damage every time you move.
TeleportBurrow: true #Teleport player above block

PreventCraftingRecipeLagExploit: true
CraftingRecipeDelay: 5 # in ticks

# DISABLE AT CERTAIN TPS
Redstone: 16 # Freezes all redstone until tps is above this amount.

KickPlayerIfTemporary: true
TemporaryKickMessage: "sus"